# sample configuration file for bitfloor-ruby
# put your keys in the appropriate spaces bellow
# rename this file config.yml
development:
  url: 'https://api.testbed.bitfloor.com'
  key: 'your key here'
  secret: 'your secret here'
production:
  url: 'https://api.bitfloor.com'
  key: 'your key here'
  secret: 'your secret here'
